micronaut:
  application:
    name: ${project.artifactId}

  ## https://docs.micronaut.io/latest/guide/index.html#caching
  caches:
    thing:
      expire-after-access: P1d

## see https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
endpoints:
  all:
    port: 8090
    path: /endpoints
    sensitive: false
  health:
    details-visible: ANONYMOUS
  caches:
    enabled: true

## see https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc
datasources:
  default:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:${datasources.default.database};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    database: metric-receiver
    username: micronaut
    password: changeMe
    dialect: H2

## see https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html
flyway:
  datasources:
    default:
      locations: classpath:database/default

## RabbitMQ
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  automatic-recovery-enabled: true
  topology-recovery-enabled: true
  network-recovery-interval: 5000
  queue:
    event: metric.receiver.event
    telemetry: metric.receiver.telemetry

## InfluxDB
influxdb:
  url: http://${influxdb.host:localhost}:${influxdb.port:8086}
  database: kiwios
  username: nope
  password: nope
  batch-enabled: true
  batch-actions-limit: 1000
  batch-buffer-limit: 10000
  batch-flush-duration: 1000
  batch-jitter-duration: 0
